apiVersion: apps/v1
kind: Deployment
metadata:
  name: html-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: html-page
  template:
    metadata:
      labels:
        app: html-page
    spec:
      containers:
        - name: nginx-container
          image: your-dockerhub-username/simple-html:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: html-service
spec:
  selector:
    app: html-page
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
